server:
  port: 8080
message-processor:
  url: http://localhost:8081
spring:
  application:
    name: srv
  datasource:
    url: jdbc:postgresql://localhost:5432/task_manager
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  data:
    mongodb:
      uri: mongodb://localhost:27017/task_manager
  flyway:
    enabled: true
    locations: classpath:db/migration
  security:
    jwt:
      secret: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    template:
      exchange: task_exchange
      routing-key: task_status_key
      default-receive-queue: task_status_queue


